mvn package
echo "*************************************"
echo "Ejemplo patron AbstractFactory "
echo "*************************************"
mvn exec:java -Dexec.mainClass="mx.adsi.designpatterns.abstractfactory.AbstractCarFactoryDemo"
echo "*************************************"
echo "Ejemplo patron Adapter "
echo "*************************************"
mvn exec:java -Dexec.mainClass="mx.adsi.designpatterns.adapter.AdapterPatternMain"
echo "*************************************"
echo "Ejemplo patron Decorator"
echo "*************************************"
mvn exec:java -Dexec.mainClass="mx.adsi.designpatterns.decorator.OsuDecoratorMain"
echo "*************************************"
echo "Ejemplo patron Memento"
echo "*************************************"
mvn exec:java -Dexec.mainClass="mx.adsi.designpatterns.memento.MementoExampleMain"
echo "*************************************"
echo "Ejemplo patron Proxy"
echo "*************************************"
mvn exec:java -Dexec.mainClass="mx.adsi.designpatterns.proxy.ProxyPatternMain"
echo "*************************************"
echo "Ejemplo patron Visitor"
echo "*************************************"
mvn exec:java -Dexec.mainClass="mx.adsi.designpatterns.visitor.ServerMonitoringSystem"
